[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "B2tj6s4Nco5rSyEFFqw6Dkc5NsY4upRB5Nntwo5KabiA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/jacqline/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"